language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=c8d9d6be730725a6b7a02073283353c5756640ef71753a06bb96c77c7447266f"
install:
  - "npm install grunt-cli codeclimate-test-reporter -g"
  - "npm install"
script:
  - "gulp ci"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "iojs-v1"
  - "iojs-v2"
cache:
  directories:
    - 'node_modules'
